quick_transfer/apps/account/urls.py
from django.urls import path

from .import views

app_name = 'account'

urlpatterns = [
  path('',views.Details.as_view(), name='home'),
  path('load/',views.Load.as_view(), name='load'),
  path('search/',views.Search.as_view(), name='search')
]

quick_transfer/apps/reason/urls.py
from django.urls import path

from .import views

app_name = 'reason'

urlpatterns = [
  
]

quick_transfer/apps/transaction/urls.py
from django.urls import path

from .import views

app_name = 'transaction'

urlpatterns = [
  
]

quick_transfer/apps/user/urls.py
from django.urls import path
from django.contrib.auth import views as views_django

from .import views

app_name = 'user'

urlpatterns = [
    path('login/', views_django.LoginView.as_view(template_name="user/login.html"), name="login"),
    path('signup', views.NewUser.as_view(), name='signup'),
    path('logout/', views_django.logout_then_login, name="logout"),
]

quick_transfer/quick_transfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('account:home')),
    path('user/', include('apps.user.urls')),
    path('account/', include("apps.account.urls")),
    path('transaction/', include("apps.transaction.urls")),
    path('reason/', include("apps.reason.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quick_transfer/apps/account/models.py
from django.db import models
from apps.user.models import User

class Account(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
  balance = models.FloatField(default=0.00)
  favorites = models.ManyToManyField('self')
  
  def __str__(self):
    return self.user.username

quick_transfer/apps/reason/models.py
from django.db import models

class Reason(models.Model):
  pass

quick_transfer/apps/transaction/models.py
from django.db import models
from apps.account.models import Account
from apps.reason.models import Reason

class Transaction(models.Model):
  emitter = models.ForeignKey(Account, related_name='transactions_sent', on_delete=models.CASCADE)
  receiver = models.ForeignKey(Account, related_name='transactions_received', on_delete=models.CASCADE)
  amount = models.FloatField(default=0.00)
  date = models.DateTimeField(auto_now_add=True)
  reason = models.ForeignKey(Reason,on_delete=models.CASCADE)

quick_transfer/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    dni = models.IntegerField(null=True)
    img_profile = models.ImageField(upload_to='avatars/', null=True, blank=True)
    is_admin = models.BooleanField(default=False)

quick_transfer/apps/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from apps.account.models import Account

class FormNewUser(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'dni', 'img_profile']
    
    def save(self, commit = True):
        if commit:
            user = super().save()
            Account.objects.create(user=user)
        return user

quick_transfer/apps/account/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import UpdateView

from .models import Account

class Details(LoginRequiredMixin,TemplateView):
  template_name = 'account/home.html'
  user = None
  
  def dispatch(self, request, *args, **kwargs):
    self.user = request.user
    return super().dispatch(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
      ctx = super(Details, self).get_context_data(**kwargs)
      ctx['account'] = self.user.account
      return ctx

class Load(LoginRequiredMixin,TemplateView):
  template_name = 'account/load.html'
  user = None
  
  def dispatch(self, request, *args, **kwargs):
    self.user = request.user
    return super().dispatch(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
      ctx = super(Load, self).get_context_data(**kwargs)
      ctx['account'] = self.user.account
      return ctx
  
  def post(self, request, *args, **kwargs):
    amount = int(request.POST['amount'])
    account = self.user.account
    account.balance = account.balance + amount
    account.save()
    return redirect('account:home')
  
class Search(LoginRequiredMixin,TemplateView):
  model = Account
  user = None
  
  def dispatch(self, request, *args, **kwargs):
    self.user = request.user
    return super().dispatch(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
      ctx = super(Load, self).get_context_data(**kwargs)
      ctx['account'] = self.user.account
      return ctx
  
  def get(self, request, *args, **kwargs):
    
    return redirect('account:home')

quick_transfer/apps/reason/views.py
from django.shortcuts import render

# Create your views here.

quick_transfer/apps/transaction/views.py
from django.shortcuts import render

# Create your views here.

quick_transfer/apps/user/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .forms import FormNewUser

from .models import User

class NewUser(CreateView):
    template_name = 'user/signup.html'
    model = User
    form_class = FormNewUser
    success_url = reverse_lazy('login')
    
    def get_context_data(self, **kwargs):
        ctx = super(NewUser, self).get_context_data(**kwargs)
        return ctx
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

quick_transfer/templates/form.html
{% load filters %}

{% for field in form %}
    <div>
        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
            {{field.label}}
            {{field|add_class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }}
        </label>
    </div>
{% endfor %}

quick_transfer/templates/headers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="w-[100vw] h-[100vh] bg-[#D1D5DB]">
  {% block content %}
  {% endblock %}
</body>
</html>

quick_transfer/templates/user/login.html
{% extends "headers.html" %}
{% block title %}Iniciar Sesión{% endblock %}
{% block content %}
<main>
    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
                <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">
                QuickTransfer
            </a>
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Ingresa a tu cuenta
                    </h1>
                    <form class="space-y-4 md:space-y-6" action="" method="post">{% csrf_token %}
                        {% include "form.html" with form=form %}

                        <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Ingresar</button>
                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            ¿No tenes una cuenta? <a href="{% url "user:signup" %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Crea tu cuenta</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
      </section>
</main>
{% endblock  %}

quick_transfer/templates/user/signup.html
{% extends "headers.html" %}
{% block title %}Crear cuenta{% endblock %}
{% block content %}
<main>
    <section class="bg-gray-50 dark:bg-gray-900 p-4">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto lg:py-0">
            <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
                <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">
                QuickTransfer    
            </a>
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Crear una cuenta
                    </h1>
                    {{form.errors}}
                    <form class="space-y-4 md:space-y-6" action="" method="post">{% csrf_token %}
                        {% include "form.html" with form=form %}
                        <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Crear una cuenta</button>
                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            ¿Ya tienes una cuenta? <a href="{% url "user:login" %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Ingresa acá</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
      </section>
</main>
{% endblock %}